# Generated by Django 2.2.4 on 2019-09-03 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Modelo de Especialidade',
                'verbose_name_plural': 'Modelo de Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.CharField(max_length=255, unique=True)),
                ('data', models.DateField(verbose_name='Data')),
                ('local', models.CharField(max_length=255, unique=True, verbose_name='Local')),
                ('finalizado', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('data_nascimento', models.DateTimeField(verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_vagas', models.PositiveIntegerField(unique=True, verbose_name='Quantidade de Vagas')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='api.Especialidade', verbose_name='Especialidades')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='api.Evento', verbose_name='Evento')),
                ('participante', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.User', verbose_name='Participante')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='api.User', verbose_name='Owner'),
        ),
        migrations.CreateModel(
            name='CandidatoVaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_desempenho', models.PositiveIntegerField(unique=True, verbose_name='Nota  de Desempenho')),
                ('state_vaga', models.PositiveSmallIntegerField(choices=[(1, 'DEFERIDO'), (2, 'NÃO DEFERIDO'), (3, 'NÃO AVALIADO')], verbose_name='Status da Vaga')),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='Candidato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos_vaga', to='api.Vaga', verbose_name='Vaga')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_avaliacao_evento', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Nota da Avaliação')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_evento', to='api.Evento', verbose_name='Evento')),
            ],
        ),
    ]
