# Generated by Django 2.2.4 on 2019-09-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaoevento',
            name='nota_avaliacao_evento',
        ),
    ]
