# Generated by Django 2.2.4 on 2019-09-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_avaliacaoevento_nota_avaliacao_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
