# Generated by Django 2.2.4 on 2019-09-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190903_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='participante',
        ),
    ]
