# Generated by Django 2.2.4 on 2019-09-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_vaga_participante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatovaga',
            name='nota_desempenho',
            field=models.PositiveIntegerField(blank=True, verbose_name='Nota  de Desempenho'),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
