# Generated by Django 2.2.4 on 2019-09-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190903_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatovaga',
            name='nota_desempenho',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota  de Desempenho'),
        ),
    ]
