# Generated by Django 2.2.4 on 2019-10-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190903_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatovaga',
            name='state_vaga',
            field=models.PositiveSmallIntegerField(choices=[(1, 'DEFERIDO'), (2, 'INDEFERIDO'), (3, 'NAOAVALIADO')], verbose_name='Status da Vaga'),
        ),
    ]
